AnguHashBlog/angular

angular-app/src/app/graphql.operations.ts

hashnode blog url changed to 'hashnode-blog.hashnodeng.com'

---

CONTRIBUTING.md

contributing.md updated

---

angular-app/src/app/app.component.html
angular-app/src/app/app.component.ts
angular-app/src/app/components/footer/footer.component.ts
angular-app/src/app/components/header/header.component.html
angular-app/src/app/components/header/header.component.scss
angular-app/src/app/components/header/header.component.ts
angular-app/src/app/components/layout/layout.component.html
angular-app/src/app/components/post-details/post-details.component.html
angular-app/src/app/components/post-details/post-details.component.scss
angular-app/src/app/components/post-details/post-details.component.ts
angular-app/src/app/components/posts/posts.component.ts
angular-app/src/app/components/series/series.component.ts
angular-app/src/app/components/sidenav/sidenav.component.ts
angular-app/src/app/graphql.operations.ts
angular-app/src/app/partials/follow-dialog/follow-dialog.component.html
angular-app/src/app/partials/settings-dialog/settings-dialog.component.html
angular-app/src/app/partials/settings-dialog/settings-dialog.component.scss
angular-app/src/app/partials/settings-dialog/settings-dialog.component.spec.ts
angular-app/src/app/partials/settings-dialog/settings-dialog.component.ts
angular-app/src/app/services/blog.service.ts
angular-app/src/app/services/modal.service.ts
angular-app/src/styles.scss

closes #34 
- added another control with the `gear` icon in the main header component 
- placed it between the theme control and search
- gave it a class of `settings` 
- added on click event that opens up a new modal created in the `partials` folder named `settings-dialog`
- the settings dialog has brief text explaining that users can try the live demo with their own Hashnode Blog URL 👏
- added conditional rendering to show an input and a `change` button if the blog url has not been changed
- if the url is the default another view shows with a `reset` button
- the input is connected to a `[(ngModel)]` to collect the value
- updated every query in the `graphql.operations.ts` to take a `host` parameter which is going to be the blog URL 
- removed the `${BLOG_HOST}` variable from that file …

Change blog url

---

angular-app/src/app/components/posts/posts.component.scss
angular-app/src/app/components/posts/posts.component.ts
angular-app/src/app/components/series/series.component.html
angular-app/src/app/components/series/series.component.scss
angular-app/src/app/components/series/series.component.ts
angular-app/src/app/graphql.operations.ts
angular-app/src/app/services/blog.service.ts

closes #40 
Fix `load more` button in `series` should load more posts just from that `series`

fix(series): load more posts only from the series

---

angular-app/src/app/components/posts/posts.component.ts
angular-app/src/app/components/series/series.component.ts
angular-app/src/app/models/blog-info.ts
angular-app/src/app/models/post.ts
angular-app/src/app/services/blog.service.ts

fix(models): placing the interface in the sorrect file

---

.github/label-actions.yml

workflow-1

---

.github/workflows/label-actions.yml

workflow-2

---

angular-app/src/app/components/sidenav/sidenav.component.html
angular-app/src/app/components/sidenav/sidenav.component.scss
angular-app/src/app/components/sidenav/sidenav.component.ts

modified:   angular-app/src/app/components/sidenav/sidenav.component.html
modified:   angular-app/src/app/components/sidenav/sidenav.component.scss
modified:   angular-app/src/app/components/sidenav/sidenav.component.ts
closes #

Add social link back to the sidnav

---

angular-app/src/app/components/posts/posts.component.html
angular-app/src/app/components/posts/posts.component.ts
angular-app/src/app/components/series/series.component.html
angular-app/src/app/components/series/series.component.ts

closes #30
Add right click open link in a new tab for individual blog posts in posts and series

feature: Add right click open link in a new tab for individual blog posts in posts and series

---

angular-app/src/app/graphql.operations.ts
angular-app/src/app/models/post.ts

graphql operations

---

angular-app/src/app/graphql.operations.ts

Publication id added 

---

angular-app/src/app/app.routes.ts
angular-app/src/app/components/header/header.component.html
angular-app/src/app/components/posts/posts.component.html
angular-app/src/app/components/series/series.component.html
angular-app/src/app/components/series/series.component.ts

revert of routes needs further looking into

---

angular-app/src/app/components/sidenav/sidenav.component.html

closes #
- missed it out in the previous PR

minor fix sidenav routerlinks

---

angular-app/src/app/components/post-details/post-details.component.ts
angular-app/src/app/partials/share-dialog/share-dialog.component.ts
angular-app/src/app/services/blog.service.ts
angular-app/src/index.html

Working more on the dynamic og:image

---

angular-app/src/app/app.routes.ts
angular-app/src/app/components/post-details/post-details.component.ts
angular-app/src/app/models/post.ts
angular-app/src/app/partials/share-dialog/share-dialog.component.ts
angular-app/src/app/services/blog.service.ts

clearing up

---

angular-app/src/app/app.component.ts
angular-app/src/app/components/post-details/post-details.component.ts
angular-app/src/index.html

trying in the relevant components must test deployed

---

angular-app/src/app/app.component.ts
angular-app/src/app/components/post-details/post-details.component.ts

just in case

---

angular-app/src/app/app.routes.ts
angular-app/src/app/components/posts/posts.component.html
angular-app/src/app/components/series/series.component.html

 'post/' returned to route, wildcard redirect added

---

.github/workflows/issue.yml
.github/workflows/triage.yml
angular-app/src/index.html

trying some workflows

---

angular-app/CHANGELOG.md

feat(docs): changelog generated

---

angular-app/src/app/components/header/header.component.scss
angular-app/src/app/components/posts/posts.component.scss
package-lock.json

feature(posts): responsiveness

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

docs(templates): issue and bug template updates

---

angular-app/src/app/components/header/header.component.scss
angular-app/src/app/components/posts/posts.component.scss
angular-app/src/app/components/series/series.component.scss
angular-app/src/app/components/sidenav/sidenav.component.scss
angular-app/src/app/partials/follow-dialog/follow-dialog.component.scss
angular-app/src/app/partials/settings-dialog/settings-dialog.component.scss
angular-app/src/app/partials/share-dialog/share-dialog.component.scss
angular-app/src/styles.scss

fix(responsiveness): corrections after view on actual device

---

angular-app/src/app/components/header/header.component.html

fix(header): blog-title how it was supposed to be

---

angular-app/src/app/components/post-details/post-details.component.ts

feat(post-details): removing unused code

---

angular-app/src/app/partials/settings-dialog/settings-dialog.component.html
angular-app/src/app/partials/settings-dialog/settings-dialog.component.scss
angular-app/src/app/partials/settings-dialog/settings-dialog.component.ts
angular-app/src/styles.scss

feat(settings-dialog): input validations and error handling

---

angular-app/src/app/partials/settings-dialog/settings-dialog.component.html
angular-app/src/app/partials/settings-dialog/settings-dialog.component.ts

fix(settings-dialog): validations and error handling adjustment

---

angular-app/src/app/components/post-details/post-details.component.ts

Feature: Set the page position for post-details to always start at the very top OnInit
closes #69 

Feature: Set the page position for post-details to always start at the very top OnInit

---

angular-app/src/app/graphql.operations.ts
angular-app/src/app/models/post.ts

closes #116 
- fixing inconsistency in GraphQL query for author data

fix(graphql.operations.ts): inconsistency in GraphQL query for author data

---

angular-app/src/app/components/post-details/post-details.component.html

fix(post-details): post.author.username
